version: "3"

services:
  node0:
    image: ${ETHERMINT_IMAGE}
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    volumes:
      - ./client-data/node0/ethermintd:/root/.ethermintd
    networks:
      - ethermint

  node1:
    image: ${ETHERMINT_IMAGE}
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    volumes:
      - /root/.ethermintd:/root/.ethermintd
      # - ./client-data/node1/ethermintd:/root/.ethermintd
    networks:
      - ethermint

  node2:
    image: ${ETHERMINT_IMAGE}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./client-data/node2/ethermintd:/root/.ethermintd
    networks:
      - ethermint

  node3:
    image: ${ETHERMINT_IMAGE}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./client-data/node3/ethermintd:/root/.ethermintd
    networks:
      - ethermint

networks:
  ethermint:
